name: SAMS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install pandas matplotlib tabulate python-dotenv openai scipy
        
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8 (PEP 8 Check)
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Basic Smoke Test (Verify modules load)
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        python -c "from app import core, ui, viz, ai, config; print('✅ Modules loaded successfully')"